CREATE TABLE "Cost" (
  "id" int4 NOT NULL,
  "title" varchar(255) NOT NULL,
  "maxPerson" int2 NOT NULL,
  "timeStart" timestamptz NOT NULL,
  "idRoomType" int4 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "CostDetail" (
  "id" int4 NOT NULL,
  "cost" decimal(10,2) NOT NULL,
  "numberOfPerson" int2 NOT NULL,
  "idCost" int4 NOT NULL,
  "surcharge" decimal(20,2),
  PRIMARY KEY ("id")
);

CREATE TABLE "Booking" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "customerName" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "phone" varchar(10) COLLATE "pg_catalog"."default" NOT NULL,
  "address" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "status" int2 NOT NULL,
  "prepay" numeric,
  "paid" int2 NOT NULL,
  "checkinDate" date,
  "checkoutDate" date,
  "typeofBooking" int2,
  "typeofPayment" int2,
  "totalDiscount" numeric,
  "totalServiceAmount" numeric,
  "totalPayment" numeric,
  "totalRoomBooked" numeric,
  "idEmployee" int4 NOT NULL,
  "idCustomer" int4 NOT NULL,
  CONSTRAINT "Booking_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "Booking" OWNER TO "postgres";

CREATE TABLE "Booking_RoomType" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "numberRoom" int2,
  "idBooking" int4 NOT NULL,
  "idRoomType" int4 NOT NULL,
  CONSTRAINT "Booking_RoomType_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "Booking_RoomType" OWNER TO "postgres";

CREATE TABLE "Customer" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "uid" uuid NOT NULL,
  "fullName" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "identifyNumber" varchar(15) COLLATE "pg_catalog"."default" NOT NULL,
  "time" int2,
  "idInfo" int4 NOT NULL,
  "idUser" int4 NOT NULL,
  CONSTRAINT "Visistor_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Visistor_idInfo_key" UNIQUE ("idInfo"),
  CONSTRAINT "Visistor_idUser_key" UNIQUE ("idUser")
);
ALTER TABLE "Customer" OWNER TO "postgres";

CREATE TABLE "Department" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "uid" uuid NOT NULL,
  CONSTRAINT "Department_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "Department" OWNER TO "postgres";

CREATE TABLE "Employee" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "firstName" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "lastName" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "active" bool NOT NULL,
  "idDepartment" int4 NOT NULL,
  "idInfo" int4 NOT NULL,
  "idUser" int4 NOT NULL,
  CONSTRAINT "Employee_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Employee_idInfo_key" UNIQUE ("idInfo"),
  CONSTRAINT "Employee_idUser_key" UNIQUE ("idUser")
);
ALTER TABLE "Employee" OWNER TO "postgres";

CREATE TABLE "Image" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "path" varbit(255) NOT NULL,
  "idRoomType" int4 NOT NULL,
  CONSTRAINT "Image_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "Image" OWNER TO "postgres";
COMMENT ON TABLE "Image" IS 'Hình ảnh loại phòng';

CREATE TABLE "Info" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "dob" date NOT NULL,
  "email" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "gender" int2 NOT NULL,
  "address" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "phone" varchar(10) COLLATE "pg_catalog"."default" NOT NULL,
  CONSTRAINT "Info_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "Info" OWNER TO "postgres";

CREATE TABLE "Permision" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "value" int8 NOT NULL,
  CONSTRAINT "Permision_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "Permision" OWNER TO "postgres";

CREATE TABLE "Rating" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "number" int2 NOT NULL,
  "idUser" int4 NOT NULL,
  CONSTRAINT "Rating_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Rating_idUser_key" UNIQUE ("idUser")
);
ALTER TABLE "Rating" OWNER TO "postgres";

CREATE TABLE "Role" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "value" int8 NOT NULL,
  "code" varchar(10) COLLATE "pg_catalog"."default" NOT NULL,
  CONSTRAINT "Role_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "Role" OWNER TO "postgres";

CREATE TABLE "Role_Permision" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "idRole" int4 NOT NULL,
  "idPermision" int4 NOT NULL,
  CONSTRAINT "Role_Permision_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "Role_Permision" OWNER TO "postgres";

CREATE TABLE "Room" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "roomNumber" varchar(5)[] COLLATE "pg_catalog"."default" NOT NULL,
  "deleted" bool,
  "status" int2 NOT NULL,
  "idRoomType" int4 NOT NULL,
  CONSTRAINT "Room_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "Room" OWNER TO "postgres";
COMMENT ON TABLE "Room" IS 'Phòng';

CREATE TABLE "RoomBookingDetail" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "numberOfPerson" int4 NOT NULL,
  "idRoom" int4 NOT NULL,
  "idBooking" int4 NOT NULL,
  CONSTRAINT "RoomBookingDetail_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "RoomBookingDetail" OWNER TO "postgres";

CREATE TABLE "RoomService" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "cost" numeric NOT NULL,
  CONSTRAINT "RoomService_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "RoomService" OWNER TO "postgres";
COMMENT ON TABLE "RoomService" IS 'Loại phòng';

CREATE TABLE "RoomType" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "totalRoom" int2 NOT NULL,
  CONSTRAINT "RoomType_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "RoomType" OWNER TO "postgres";
COMMENT ON TABLE "RoomType" IS 'Loại phòng';

CREATE TABLE "RoomType_Service" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "idRoomType" int4 NOT NULL,
  "idRoomService" int4 NOT NULL,
  CONSTRAINT "RoomType_Service_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "RoomType_Service" OWNER TO "postgres";

CREATE TABLE "RoomTypeDetail" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "cost" numeric NOT NULL,
  "adultNumber" int2 NOT NULL,
  "childNumber" int2 NOT NULL,
  "description" text COLLATE "pg_catalog"."default" NOT NULL,
  "smokeFriendly" bool NOT NULL,
  "petFriendly" bool NOT NULL,
  "deleted" bool,
  "idRoomType" int4 NOT NULL,
  CONSTRAINT "RoomTypeDetail_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "RoomTypeDetail_idRoomType_key" UNIQUE ("idRoomType")
);
ALTER TABLE "RoomTypeDetail" OWNER TO "postgres";
COMMENT ON TABLE "RoomTypeDetail" IS 'Chi tiết loại phòng';

CREATE TABLE "ServiceBill" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "customerName" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "totalAmount" numeric NOT NULL,
  "uid" uuid NOT NULL,
  "roomNumber" varchar(5) COLLATE "pg_catalog"."default" NOT NULL,
  "idBooking" int4,
  CONSTRAINT "ServiceBill_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "ServiceBill" OWNER TO "postgres";
COMMENT ON TABLE "ServiceBill" IS 'Loại phòng';

CREATE TABLE "ServiceBill_RooomService" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "idRoomService" int4 NOT NULL,
  "idServiceBill" int4 NOT NULL,
  CONSTRAINT "ServiceBill_RooomService_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "ServiceBill_RooomService" OWNER TO "postgres";

CREATE TABLE "User" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deleted" bool,
  "uid" uuid NOT NULL,
  "username" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "active" bool NOT NULL,
  "avatar" varbit(255) NOT NULL,
  CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "User" OWNER TO "postgres";

CREATE TABLE "User_Role" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "idRole" int4 NOT NULL,
  "idUser" int4 NOT NULL,
  CONSTRAINT "User_Role_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "User_Role" OWNER TO "postgres";

ALTER TABLE "Cost" ADD CONSTRAINT "fk_Cost_RoomType_1" FOREIGN KEY ("idRoomType") REFERENCES "RoomType" ("id");
ALTER TABLE "CostDetail" ADD CONSTRAINT "fk_CostDetail_Cost_1" FOREIGN KEY ("idCost") REFERENCES "Cost" ("id");
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_idCustomer_fkey" FOREIGN KEY ("idCustomer") REFERENCES "Customer" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Booking" ADD CONSTRAINT "Booking_idEmployee_fkey" FOREIGN KEY ("idEmployee") REFERENCES "Employee" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Booking_RoomType" ADD CONSTRAINT "Booking_RoomType_idBooking_fkey" FOREIGN KEY ("idBooking") REFERENCES "Booking" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Booking_RoomType" ADD CONSTRAINT "Booking_RoomType_idRoomType_fkey" FOREIGN KEY ("idRoomType") REFERENCES "RoomType" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Customer" ADD CONSTRAINT "fk_Visistor_Info_1" FOREIGN KEY ("idInfo") REFERENCES "Info" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Customer" ADD CONSTRAINT "fk_Visistor_User_1" FOREIGN KEY ("idUser") REFERENCES "User" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_idDepartment_fkey" FOREIGN KEY ("idDepartment") REFERENCES "Department" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Employee" ADD CONSTRAINT "fk_Employee_Info_1" FOREIGN KEY ("idInfo") REFERENCES "Info" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Employee" ADD CONSTRAINT "fk_Employee_User_1" FOREIGN KEY ("idUser") REFERENCES "User" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Image" ADD CONSTRAINT "Image_idRoomType_fkey" FOREIGN KEY ("idRoomType") REFERENCES "RoomType" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Rating" ADD CONSTRAINT "Rating_idUser_fkey" FOREIGN KEY ("idUser") REFERENCES "User" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Role_Permision" ADD CONSTRAINT "Role_Permision_idPermision_fkey" FOREIGN KEY ("idPermision") REFERENCES "Permision" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Role_Permision" ADD CONSTRAINT "Role_Permision_idRole_fkey" FOREIGN KEY ("idRole") REFERENCES "Role" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Room" ADD CONSTRAINT "Room_idRoomType_fkey" FOREIGN KEY ("idRoomType") REFERENCES "RoomType" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "RoomBookingDetail" ADD CONSTRAINT "RoomBookingDetail_idRoom_fkey" FOREIGN KEY ("idRoom") REFERENCES "Room" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "RoomBookingDetail" ADD CONSTRAINT "fk_RoomBookingDetail_Booking_1" FOREIGN KEY ("idBooking") REFERENCES "Booking" ("id");
ALTER TABLE "RoomType_Service" ADD CONSTRAINT "RoomType_Service_idRoomService_fkey" FOREIGN KEY ("idRoomService") REFERENCES "RoomService" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "RoomType_Service" ADD CONSTRAINT "RoomType_Service_idRoomType_fkey" FOREIGN KEY ("idRoomType") REFERENCES "RoomType" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "RoomTypeDetail" ADD CONSTRAINT "fk_RoomTypeDetail_RoomType_1" FOREIGN KEY ("idRoomType") REFERENCES "RoomType" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "ServiceBill" ADD CONSTRAINT "fk_ServiceBill_Booking_1" FOREIGN KEY ("idBooking") REFERENCES "Booking" ("id");
ALTER TABLE "ServiceBill_RooomService" ADD CONSTRAINT "ServiceBill_RooomService_idRoomService_fkey" FOREIGN KEY ("idRoomService") REFERENCES "RoomService" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "ServiceBill_RooomService" ADD CONSTRAINT "ServiceBill_RooomService_idServiceBill_fkey" FOREIGN KEY ("idServiceBill") REFERENCES "ServiceBill" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "User_Role" ADD CONSTRAINT "User_Role_idRole_fkey" FOREIGN KEY ("idRole") REFERENCES "Role" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "User_Role" ADD CONSTRAINT "User_Role_idUser_fkey" FOREIGN KEY ("idUser") REFERENCES "User" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

